apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  labels:
    app: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: jaezeu/ms_v3:latest
        ports:
        - containerPort: 8484
        - containerPort: 7575
        - containerPort: 7576
        - containerPort: 7577
