apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms
  name: ms-service
spec:
  ports:
  - name: port-1
    port: 8484
    protocol: TCP
    targetPort: 8484
  - name: port-2
    port: 7575
    protocol: TCP
    targetPort: 7575
  - name: port-3
    port: 7576
    protocol: TCP
    targetPort: 7576
  - name: port-4
    port: 7577
    protocol: TCP
    targetPort: 7577
  selector:
    app: ms
  type: LoadBalancer
status:
  loadBalancer: {}
